services:
  redis:
    image: redis:alpine
  
  vote:
    image: vote-app
    ports:
      - 5000:80

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres

  worker:
    image: worker-app

  result:
    image: result-app
    ports:
      - 4000:80
