version: "3"
services:
  redis:
    image: redis:alpine
  
  vote:
    image: vote-app
    ports:
      - 5080:80

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres

  worker:
    image: worker-app

  result:
    image: result-app
    ports:
      - 4000:80
    volumes:
      - shared_volume:/usr/local/app/data

  apache-server:
    image: voting-apache-server
    ports:
      - 80:80
    volumes:
      - shared_volume:/usr/local/apache2/htdocs/data

volumes:
  shared_volume:
